import { Campaign, RTEContent } from '../types';

// Helper to create simple RTE content
function createRTEContent(text: string): RTEContent {
  return {
    type: 'doc',
    uid: `rte_${Math.random().toString(36).slice(2, 9)}`,
    children: [
      {
        type: 'p',
        uid: `p_${Math.random().toString(36).slice(2, 9)}`,
        children: [{ type: 'text', text }],
      },
    ],
  };
}

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    uid: 'blt_campaign_001',
    title: 'Summer Sale 2024',
    key_messages: createRTEContent('Save up to 50% on all summer products! Limited time offers on outdoor furniture, grills, and patio accessories.'),
    campaign_goals: createRTEContent('Increase Q3 revenue by 25% through targeted promotions. Drive 40% more traffic to summer category pages.'),
    start_date: '2024-06-01',
    end_date: '2024-08-31',
    contributors: [],
    budget: '$50,000',
    status: 'active',
    channels: ['Web', 'Email', 'Social'],
    assets: [],
    created_at: '2024-05-15T10:00:00Z',
    updated_at: '2024-06-20T14:30:00Z',
    created_by: 'sarah.johnson',
    updated_by: 'sarah.johnson',
    locale: 'en-us',
  },
  {
    uid: 'blt_campaign_002',
    title: 'Product Launch: Smart Home Hub',
    key_messages: createRTEContent('Introducing the next generation of smart home control. One hub to rule them all - seamless integration with 500+ devices.'),
    campaign_goals: createRTEContent('Generate 10,000 pre-orders in the first month. Achieve 80% positive sentiment on social media coverage.'),
    start_date: '2024-09-01',
    end_date: '2024-10-31',
    contributors: [],
    budget: '$100,000',
    status: 'active',
    channels: ['Web', 'Native Mobile', 'Social', 'Ads'],
    assets: [],
    created_at: '2024-07-01T09:00:00Z',
    updated_at: '2024-08-15T11:00:00Z',
    created_by: 'mike.chen',
    updated_by: 'mike.chen',
    locale: 'en-us',
  },
  {
    uid: 'blt_campaign_003',
    title: 'Brand Awareness - Q4',
    key_messages: createRTEContent('Building trust through transparency. Our commitment to sustainability and ethical sourcing.'),
    campaign_goals: createRTEContent('Increase brand recognition by 15% in target demographics. Grow social media following by 25%.'),
    start_date: '2024-10-01',
    end_date: '2024-12-31',
    contributors: [],
    budget: '$75,000',
    status: 'paused',
    channels: ['Web', 'Social', 'Ads'],
    assets: [],
    created_at: '2024-08-20T14:00:00Z',
    updated_at: '2024-09-05T16:00:00Z',
    created_by: 'emma.wilson',
    updated_by: 'emma.wilson',
    locale: 'en-us',
  },
  {
    uid: 'blt_campaign_004',
    title: 'Holiday Gift Guide 2023',
    key_messages: createRTEContent('Find the perfect gift for everyone on your list. Curated collections for all budgets and interests.'),
    campaign_goals: createRTEContent('Drive 35% of annual revenue in Q4. Increase average order value by 20% during holiday period.'),
    start_date: '2023-11-01',
    end_date: '2023-12-31',
    contributors: [],
    budget: '$80,000',
    status: 'completed',
    channels: ['Web', 'Email', 'Native Mobile', 'Ads'],
    assets: [],
    created_at: '2023-09-15T10:00:00Z',
    updated_at: '2024-01-05T09:00:00Z',
    created_by: 'alex.rivera',
    updated_by: 'alex.rivera',
    locale: 'en-us',
  },
  {
    uid: 'blt_campaign_005',
    title: 'Customer Retention Program',
    key_messages: createRTEContent('Loyalty rewards that matter. Exclusive perks for our most valued customers.'),
    campaign_goals: createRTEContent('Reduce customer churn by 10%. Increase repeat purchase rate by 15%.'),
    start_date: '2024-01-01',
    end_date: '2024-12-31',
    contributors: [],
    budget: '$45,000',
    status: 'active',
    channels: ['Email', 'Native Mobile'],
    assets: [],
    created_at: '2023-11-01T08:00:00Z',
    updated_at: '2024-06-15T10:00:00Z',
    created_by: 'jordan.lee',
    updated_by: 'jordan.lee',
    locale: 'en-us',
  },
  {
    uid: 'blt_campaign_006',
    title: 'Back to School 2024',
    key_messages: createRTEContent('Everything they need to start the year right. From tech to supplies, we have got it covered.'),
    campaign_goals: createRTEContent('Capture 20% market share in back-to-school category. Drive 50,000 new customer acquisitions.'),
    start_date: '2024-07-15',
    end_date: '2024-09-15',
    contributors: [],
    budget: '$60,000',
    status: 'completed',
    channels: ['Web', 'Email', 'Social', 'Ads'],
    assets: [],
    created_at: '2024-05-01T09:00:00Z',
    updated_at: '2024-09-20T14:00:00Z',
    created_by: 'sarah.johnson',
    updated_by: 'sarah.johnson',
    locale: 'en-us',
  },
  {
    uid: 'blt_campaign_007',
    title: 'SEO Content Strategy 2024',
    key_messages: createRTEContent('Comprehensive content strategy to dominate organic search. Focus on long-tail keywords and user intent.'),
    campaign_goals: createRTEContent('Increase organic traffic by 40%. Rank in top 3 for 100 target keywords.'),
    start_date: '2024-01-01',
    end_date: '2024-06-30',
    contributors: [],
    budget: '$25,000',
    status: 'completed',
    channels: ['Web'],
    assets: [],
    created_at: '2023-12-01T10:00:00Z',
    updated_at: '2024-07-05T16:00:00Z',
    created_by: 'mike.chen',
    updated_by: 'mike.chen',
    locale: 'en-us',
  },
];
